using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Player_Collision : Collision
{
    [SerializeField] public Player_Main player_Main_;

    public override void Congfigure_table_OnCollisionEnter2D()
    {
        Add(table_OnCollisionEnter2D_, CONSTANTS.Wall_Tag, player_Main_.player_Sound_.BumpIntoWall);
        Add(table_OnCollisionEnter2D_, CONSTANTS.Enemy_Tag, () => StartCoroutine(player_Main_.player_Move_.KnockBack()));
        Add(table_OnCollisionEnter2D_, CONSTANTS.Enemy_Tag, player_Main_.player_Color_.WhiteFlash);
        Add(table_OnCollisionEnter2D_, CONSTANTS.Enemy_Tag, UI_Main.instance_.UI_Health_.Update_UI);
    }
    public override void Congfigure_table_OnCollisionExit2D()
    {
        Add(table_OnCollisionEnter2D_, CONSTANTS.Enemy_Tag, player_Main_.player_UI_.Update_UI);

    }

    public override void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.tag == CONSTANTS.Enemy_Tag)
        {
            Enemy_Main enemy_Main = collision.gameObject.GetComponent<Enemy_Main>();
            float enemyDamage = enemy_Main.enemy_Health_.Get_Damage();
            player_Main_.player_Health_.Damage(enemyDamage);
            StartCoroutine(player_Main_.player_UI_.ShowHPChange(enemyDamage, false));

        }
        base.OnCollisionEnter2D(collision);
    }

    public override void OnTriggerEnter2D(Collider2D other)
    {
        if (other.gameObject.tag == CONSTANTS.Item_Tag)
        {
            Item_Main item_Main = other.gameObject.GetComponent<Item_Main>();
            float itemHeal = item_Main.item_Health_.Get_Heal();
            StartCoroutine(player_Main_.player_UI_.ShowHPChange(itemHeal, true));
        }
        base.OnTriggerEnter2D(other);
    }


    public override void Congfigure_table_OnTriggerEnter2D()
    {
        // the sound should be generated by the door 
        Add(table_OnTriggerEnter2D_, CONSTANTS.Door_Tag, player_Main_.player_Sound_.BumpIntoWall);
        Add(table_OnTriggerEnter2D_, CONSTANTS.Door_Tag, () => player_Main_.player_Controller_.SetIsTeleport(true));
    }
    public override void Congfigure_table_OnTriggerExit2D()
    {
        // the sound should be generated by the door 
        //Add(table_OnTriggerExit2D_, CONSTANTS.Door_Exit_Tag, Record_Main.instance_.records_Controller_.target_Position_.SetPosition);
        Add(table_OnTriggerExit2D_, CONSTANTS.Door_Exit_Tag, () => player_Main_.player_Controller_.SetIsTeleport(false));
    }
}

